<!-- R Commander Markdown Template -->

Replace with Main Title
=======================

### Your Name

### `r as.character(Sys.Date())`

```{r echo=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE, out.width=750, fig.height=8, fig.width=8)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```


```{r echo=FALSE}
# include this code chunk as-is to enable 3D graphs
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```


```{r}
Dataset <- readXL("D:/2º/Bioquímica I/Prácticas/Bioquímica (2).xlsx", 
  rownames=FALSE, header=TRUE, na="", sheet="Sheet5", stringsAsFactors=TRUE)
```


```{r}
scatterplot(micromol.PNF~ABS.a.400nm, reg.line=lm, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), xlab="Micromoles de PNF.", 
  ylab="Absorbancia a 400 nm.", main="Recta patrón de PNF.",col="green", pch=c(17), data=Dataset)
```


```{r}
legend(x = "topleft", legend = c("y=0.006x+0.048", "R^2=0.991"))
```


```{r}
scatterplot(X.abs~pH, reg.line=FALSE, smooth=FALSE, spread=FALSE, boxplots=FALSE, span=0.5, 
  ellipse=FALSE, levels=c(.5, .9), xlab="Absorbancia según el pH utilizado.", 
  ylab="% de absorbancia a 400 nm.", main="pH del tampón utilizado.",col="purple", pch=c(18), data=Dataset)
```

```{r}
scatterplot(X.abs~pH, reg.line=FALSE, smooth=FALSE, spread=FALSE, boxplots=FALSE, span=0.5, 
  ellipse=FALSE, levels=c(.5, .9), xlab="Absorbancia según el pH utilizado.", 
  ylab="% de absorbancia a 400 nm.", main="pH del tampón utilizado.",col="#FF00CC", pch=c(18), data=Dataset)
```

```{r}
scatterplot(Actividad~micromol.PNF, reg.line=FALSE, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  xlab="Concentración de sustrato (mM).", 
  ylab="Velocidad (Actividad enzimática) (U/mL).", main="Curva de Michaelis-Menten.", 
  pch=c(20), data=Dataset)
```

```{r}
scatterplot(Actividad~micromol.PNF, reg.line=FALSE, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  xlab="Concentración de sustrato (mM).", 
  ylab="Velocidad (Actividad enzimática) (U/mL).", main="Curva de Michaelis-Menten.", 
  pch=c(9),col="purple", data=Dataset)
```


```{r}
scatterplot(Actividad~micromol.PNF, reg.line=FALSE, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  xlab="Concentración de sustrato (mM).", 
  ylab="Velocidad (Actividad enzimática) (U/mL).", main="Curva de Michaelis-Menten.", 
  pch=c(10),col="purple", data=Dataset)
```


```{r}
scatterplot(Actividad~micromol.PNF, reg.line=FALSE, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  xlab="Concentración de sustrato (mM).", 
  ylab="Velocidad (Actividad enzimática) (U/mL).", main="Curva de Michaelis-Menten.", 
  pch=c(11),col="purple", data=Dataset)
```


```{r}
scatterplot(X1..Actividad~X1..S.., reg.line=lm, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  xlab="Concentración de sustrato (mM).", 
  ylab="1/Velocidad (1/Actividad enzimática) (mL/U).", main="Recta de Lineweaver-Burk.",
   pch=c(20), data=Dataset)
```

```{r}
scatterplot(X1..Actividad~X1..S.., reg.line=lm, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  xlab="1/Concentración de sustrato (mM^-1).", 
  ylab="1/Velocidad (1/Actividad enzimática) (mL/U).", 
  main="Recta de Lineweaver-Burk.",
   pch=c(1),col="green", data=Dataset)
```


```{r}
scatterplot(X1..Actividad~X1..S.., reg.line=lm, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  xlab="1/Concentración de sustrato (mM^-1).", 
  ylab="1/Velocidad (1/Actividad enzimática) (mL/U).", 
  main="Recta de Lineweaver-Burk.",
   pch=c(1),col="green", data=Dataset)
```


```{r}
legend(x = "topleft", legend = c("y=20.94x+0.15", "R^2=0.999"))
```


```{r}
scatterplot(X1..Actividad~X1..S.., reg.line=lm, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  xlab="1/Concentración de sustrato (mM^-1).", 
  ylab="1/Velocidad (1/Actividad enzimática) (mL/U).", 
  main="Recta de Lineweaver-Burk.",
   pch=c(1),col="green", data=Dataset)
```


```{r}
legend(x = "topleft", legend = c("y=20.94x+0.15", "R^2=0.999"))
```

```{r}
scatterplot(X1..Actividad~X1..S.., reg.line=lm, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  xlab="1/Concentración de sustrato (mM^-1).", 
  ylab="1/Velocidad (1/Actividad enzimática) (mL/U).", 
  main="Recta de Lineweaver-Burk.",
   pch=c(1),col="green", data=Dataset)
```


```{r}
legend(x = "topleft", legend = c("y=20.94x+0.15", "R^2=0.999"))
```


```{r}
abline(v = 0)
```


```{r}
scatterplot(X1..Actividad~X1..S.., reg.line=lm, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  xlab="1/Concentración de sustrato (mM^-1).", 
  ylab="1/Velocidad (1/Actividad enzimática) (mL/U).", 
  main="Recta de Lineweaver-Burk.",
   pch=c(1),col="green", data=Dataset)
```


```{r}
legend(x = "topleft", legend = c("y=20.94x+0.15", "R^2=0.999"))
```

```{r}
scatterplot(X1..Actividad~X1..S.., reg.line=lm, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  xlab="1/Concentración de sustrato (mM^-1).", 
  ylab="1/Velocidad (1/Actividad enzimática) (mL/U).", 
  main="Recta de Lineweaver-Burk.",
   pch=c(1),col="green", data=Dataset)
```


```{r}
legend(x = "topleft", legend = c("y=20.94x+0.15", "R^2=0.999"))
```

```{r}
scatterplot(X1..Actividad~X1..S.., reg.line=lm, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  xlab="1/Concentración de sustrato (mM^-1).", 
  ylab="1/Velocidad (1/Actividad enzimática) (mL/U).", 
  main="Recta de Lineweaver-Burk.",
   pch=c(1),col="green", data=Dataset)
```


```{r}
legend(x = "topleft", legend = c("y=20.94x+0.15", "R^2=0.999"))
```


```{r}
abline(v = 0, col="yellow")
```


```{r}
scatterplot(X1..Actividad~X1..S.., reg.line=lm, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  xlab="1/Concentración de sustrato (mM^-1).", 
  ylab="1/Velocidad (1/Actividad enzimática) (mL/U).", 
  main="Recta de Lineweaver-Burk.",
   pch=c(1),col="green", data=Dataset)
```


```{r}
legend(x = "topleft", legend = c("y=20.94x+0.15", "R^2=0.999"))
```


```{r}
abline(v = 0, col="orange")
```


```{r}
scatterplot(X.abs~T, reg.line=FALSE, smooth=FALSE, spread=FALSE, boxplots=FALSE, 
  span=0.5, ellipse=FALSE, levels=c(.5, .9), xlab="Temperatura (ºC).", 
  ylab="% de absorbancia.", main="Absorbancia según la temperatura de incubación.", 
  pch=c(20), data=Dataset)
```

```{r}
scatterplot(X.abs.1~T, reg.line=FALSE, smooth=FALSE, spread=FALSE, boxplots=FALSE, 
  span=0.5, ellipse=FALSE, levels=c(.5, .9), xlab="Temperatura (ºC).", 
  ylab="% de absorbancia.", main="Absorbancia según la temperatura de incubación.", 
  pch=c(20), data=Dataset)
```

```{r}
scatterplot(X.abs.1~T, reg.line=FALSE, smooth=FALSE, spread=FALSE, boxplots=FALSE, 
  span=0.5, ellipse=FALSE, levels=c(.5, .9), xlab="Temperatura (ºC).", 
  ylab="% de absorbancia.", main="Absorbancia según la temperatura de incubación.", 
  pch=c(16),col="purple", data=Dataset)
```


